package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"

	"github.com/thegorangers/stele/internal/report"
)

const versionUsage = `stele version prints the versions that determine generated bytes.

It names stele itself and the libraries that build the descriptor the plugins
are handed — protocompile and protobuf-go — because a change in any of them
changes the output with no plugin moving. The plugins themselves are versioned
per run, by stele generate, since only a run knows which ones it invoked.

Usage:
  stele version [flags]

Flags:
  --json    print the report as JSON instead of as a summary
`

func runVersion(_ context.Context, args []string, stdout, _ io.Writer) error {
	fs := flag.NewFlagSet("version", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	fs.Usage = func() {}

	asJSON := fs.Bool("json", false, "print the report as JSON")
	help := fs.Bool("help", false, "show this help")

	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			fmt.Fprint(stdout, versionUsage)
			return errHelp
		}
		return fmt.Errorf("%w\n\n%s", err, versionUsage)
	}
	if *help {
		fmt.Fprint(stdout, versionUsage)
		return errHelp
	}
	if rest := fs.Args(); len(rest) > 0 {
		return fmt.Errorf("unexpected argument %q; stele version takes flags only\n\n%s", rest[0], versionUsage)
	}

	rep := report.Build(nil)
	if *asJSON {
		raw, err := rep.JSON()
		if err != nil {
			return err
		}
		_, err = stdout.Write(raw)
		return err
	}
	fmt.Fprint(stdout, rep.Summary())
	return nil
}
