package migrate

import (
	"fmt"
	"path"
	"regexp"
	"strings"
)

// goInstall is one recovered `go install MODULE@VERSION` invocation.
//
// A buf.gen.yaml names a plugin and nothing else: the version that produced
// the generated bytes is written down in the Makefile, next to the command
// that installs it. Dropping it in translation hands back a manifest whose
// plugins resolve off PATH, which is the drift a declared version exists to
// end — so the Makefile is read for it, defensively, and whatever cannot be
// resolved to an exact version is reported rather than guessed.
type goInstall struct {
	// Name is the command the module installs: the base of the module path,
	// with a major-version element ignored. It is what buf.gen.yaml's local
	// field is matched against.
	Name string
	// Module is the module path as `go install` takes it, after variable
	// expansion. It is empty when expansion failed.
	Module string
	// RawModule is the module path as it was written, for messages.
	RawModule string
	// Version is the expanded version. It is empty when expansion failed or
	// when the invocation named no version at all.
	Version string
	// RawVersion is the version as it was written, for messages.
	RawVersion string
}

// exactVersion matches the versions that name one immutable release: a
// semantic version tag, which covers a pseudo-version too — it is a semantic
// version whose pre-release names the commit. A branch, a bare `latest`, and
// anything else that can mean different bytes tomorrow does not match, and is
// reported rather than carried over.
var exactVersion = regexp.MustCompile(`^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.\-]+)?(\+[0-9A-Za-z.\-]+)?$`)

// assignment matches a make variable assignment. Only the plain forms are
// recognised; a recipe line, which begins with a tab, is not one.
var assignment = regexp.MustCompile(`^([A-Za-z_][A-Za-z0-9_]*)[ \t]*(\?=|:=|::=|\+=|=)[ \t]*(.*)$`)

// makeVars are the variable assignments of a Makefile, by name.
//
// A name assigned twice with different text maps to the empty string and is
// treated as unexpandable. make would resolve it by evaluation order and by
// which flavour of assignment won; reproducing that here to pin a plugin
// version would be a guess dressed as an answer.
type makeVars map[string]string

// parseVars recovers the variable assignments of a Makefile.
func parseVars(lines []string) makeVars {
	vars := makeVars{}
	ambiguous := map[string]bool{}
	for _, line := range lines {
		if strings.HasPrefix(line, "\t") {
			continue // a recipe line, not an assignment
		}
		m := assignment.FindStringSubmatch(strings.TrimLeft(line, " "))
		if m == nil {
			continue
		}
		name, value := m[1], strings.TrimSpace(stripMakeComment(m[3]))
		if prev, seen := vars[name]; seen && prev != value {
			ambiguous[name] = true
		}
		vars[name] = value
	}
	for name := range ambiguous {
		delete(vars, name)
	}
	return vars
}

// expand resolves the variable references in s. It reports false rather than
// returning a partial expansion: anything this tool cannot evaluate — a shell
// call, a function, a substitution reference, a variable that is never
// assigned — leaves the value unknown, and an unknown version must be
// reported, not approximated.
func (v makeVars) expand(s string) (string, bool) {
	return v.expandDepth(s, 0)
}

func (v makeVars) expandDepth(s string, depth int) (string, bool) {
	if depth > 16 {
		return "", false
	}
	var out strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] != '$' {
			out.WriteByte(s[i])
			continue
		}
		if i+1 < len(s) && s[i+1] == '$' {
			out.WriteByte('$')
			i++
			continue
		}
		if i+1 >= len(s) || (s[i+1] != '(' && s[i+1] != '{') {
			return "", false
		}
		open, closer := s[i+1], byte(')')
		if open == '{' {
			closer = '}'
		}
		end := matching(s, i+1, open, closer)
		if end < 0 {
			return "", false
		}
		name := s[i+2 : end]
		if !isVarName(name) {
			return "", false // a function call, a shell call, a substitution reference
		}
		value, ok := v[name]
		if !ok {
			return "", false
		}
		expanded, ok := v.expandDepth(value, depth+1)
		if !ok {
			return "", false
		}
		out.WriteString(expanded)
		i = end
	}
	return out.String(), true
}

// matching returns the index of the closer that balances the opener at i.
func matching(s string, i int, open, closer byte) int {
	depth := 0
	for j := i; j < len(s); j++ {
		switch s[j] {
		case open:
			depth++
		case closer:
			depth--
			if depth == 0 {
				return j
			}
		}
	}
	return -1
}

func isVarName(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '_' {
			continue
		}
		return false
	}
	return true
}

// parseInstalls recovers the `go install` invocations of a Makefile, grouped
// by the command each one installs. An invocation it cannot read is reported
// rather than skipped.
//
// The two returns say different things and must not be confused. The list
// names invocations this reader could not read, one by one, and the caller
// turns each into an item a human resolves by hand. The error says the file
// as a whole is outside the model, so nothing read from it can be trusted —
// the same condition parseExports refuses, refused here in the same shape.
// Putting such a refusal in the list instead hid it: the caller aborts on the
// error the other reader returns before the list is ever printed.
func parseInstalls(makefile []byte) (map[string][]goInstall, []string, error) {
	lines := strings.Split(string(makefile), "\n")
	vars := parseVars(lines)

	out := map[string][]goInstall{}
	var unparsed []string
	logical, err := logicalLines(string(makefile))
	if err != nil {
		return nil, nil, err
	}
	for _, line := range logical {
		if !strings.Contains(line, "go install") {
			continue
		}
		args, err := fields(line)
		if err != nil {
			unparsed = append(unparsed, fmt.Sprintf("%s: %v", strings.TrimSpace(line), err))
			continue
		}
		i := indexOfInstall(args)
		if i < 0 {
			continue
		}
		spec, ok := installSpec(args[i+1:])
		if !ok {
			continue
		}
		g := parseSpec(vars, spec)
		if g.Name == "" {
			continue
		}
		out[g.Name] = append(out[g.Name], g)
	}
	return out, unparsed, nil
}

// indexOfInstall finds the "install" word of a `go install` invocation.
func indexOfInstall(args []string) int {
	for i := 0; i+1 < len(args); i++ {
		if strings.TrimPrefix(args[i], "@") == "go" && args[i+1] == "install" {
			return i + 1
		}
	}
	return -1
}

// installFlagsWithValue are the `go install` flags whose value is a separate
// argument, so that the value is not mistaken for the module argument.
var installFlagsWithValue = []string{
	"-tags", "-ldflags", "-gcflags", "-asmflags", "-gccgoflags",
	"-mod", "-modfile", "-p", "-pkgdir", "-overlay", "-toolexec", "-covermode", "-C",
}

// installSpec returns the first package argument of a `go install`.
func installSpec(args []string) (string, bool) {
	for i := 0; i < len(args); i++ {
		a := args[i]
		if !strings.HasPrefix(a, "-") {
			return a, true
		}
		if !strings.Contains(a, "=") && contains(installFlagsWithValue, a) {
			i++
		}
	}
	return "", false
}

// parseSpec turns one MODULE@VERSION argument into a recovered install.
func parseSpec(vars makeVars, spec string) goInstall {
	spec = trimShellParens(spec)
	rawModule, rawVersion := spec, ""
	if i := strings.LastIndex(spec, "@"); i > 0 {
		rawModule, rawVersion = spec[:i], spec[i+1:]
	}
	g := goInstall{RawModule: rawModule, RawVersion: rawVersion}
	if mod, ok := vars.expand(rawModule); ok {
		g.Module = mod
		g.Name = commandName(mod)
	} else {
		g.Name = commandName(rawModule)
	}
	if rawVersion != "" {
		if ver, ok := vars.expand(rawVersion); ok {
			g.Version = ver
		}
	}
	return g
}

// trimShellParens removes the closing parens of the shell group an install is
// written inside. Every measured Makefile installs a plugin from a
// `have it already || (install it)` construct, and the group's closer arrives
// glued to the module argument.
func trimShellParens(s string) string {
	for strings.HasSuffix(s, ")") && strings.Count(s, ")") > strings.Count(s, "(") {
		s = strings.TrimSuffix(s, ")")
	}
	return s
}

// commandName is the command a module path installs: its last element, with a
// major-version element ignored, which is what `go install` names the binary.
func commandName(module string) string {
	base := path.Base(module)
	if base == "." || base == "/" {
		return ""
	}
	return base
}

// pinPlugin fills in where a plugin's binary comes from, from what the
// Makefile recorded. Whatever it cannot answer is added to Unresolved and the
// plugin is left as the bare PATH lookup it already was: a manifest that
// claims a version it did not recover is worse than one that admits it has
// none.
func (m *migration) pinPlugin(name string) (module, version string) {
	installs := m.installs[name]
	if len(installs) == 0 {
		m.unresolved("buf.gen.yaml: plugin %s: no `go install` in the Makefile provides a command by that name, so no version could be recovered and the plugin is emitted as a bare PATH lookup. "+
			"Say where its binary comes from: module plus version, which only a Go program can be had by; downloads, one url and sha256 per platform, which is how a published binary is pinned; path, an explicit binary in the working copy; or leave it on PATH deliberately, pinning nothing.", name)
		return "", ""
	}

	var modules, versions []string
	for _, g := range installs {
		mod := g.Module
		if mod == "" {
			mod = g.RawModule
		}
		modules = appendUnique(modules, mod)
		ver := g.Version
		if ver == "" {
			ver = g.RawVersion
		}
		versions = appendUnique(versions, ver)
	}
	if len(modules) > 1 {
		m.unresolved("Makefile: plugin %s is installed from more than one module (%s); the Makefile does not say which one provided the binary that generated the committed code, so none was carried over",
			name, strings.Join(modules, ", "))
		return "", ""
	}
	if len(versions) > 1 {
		m.unresolved("Makefile: plugin %s is installed at more than one version (%s); the Makefile does not say which one generated the committed code, so none was carried over",
			name, strings.Join(versions, ", "))
		return "", ""
	}

	g := installs[0]
	switch {
	case g.Module == "":
		m.unresolved("Makefile: plugin %s is installed from %s, which this tool cannot expand into a module path; no module was carried over",
			name, g.RawModule)
		return "", ""
	case g.RawVersion == "":
		m.unresolved("Makefile: plugin %s is installed from %s with no version, so `go install` takes the default branch; no version was carried over. Pin an exact one",
			name, g.Module)
		return "", ""
	case g.Version == "":
		m.unresolved("Makefile: plugin %s is installed at %s, which this tool cannot expand into an exact version; no version was carried over. Pin an exact one, or say where the binary comes from another way",
			name, g.RawVersion)
		return "", ""
	case !exactVersion.MatchString(g.Version):
		m.unresolved("Makefile: plugin %s is installed at %s, which is not an exact version and can mean different bytes tomorrow; no version was carried over. Pin an exact one",
			name, g.Version)
		return "", ""
	}
	return g.Module, g.Version
}
