package lint_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/thegorangers/stele/internal/lint"
)

// TestBaselineIsDeterministicToSerialise is the lock's precedent applied here.
// People read this file in a merge request, and a generated file whose bytes
// move between two runs that found the same thing is a file whose diff nobody
// can read.
func TestBaselineIsDeterministicToSerialise(t *testing.T) {
	entries := []lint.BaselineEntry{
		{Rule: "stele/enum_value_prefix", Path: "example/v1/b.proto", Subject: "example.v1.PAID"},
		{Rule: "stele/enum_value_prefix", Path: "example/v1/a.proto", Subject: "example.v1.PLACED"},
		{Rule: "stele/syntax_declared", Path: "example/v1/a.proto"},
		{Rule: "stele/enum_value_prefix", Path: "example/v1/a.proto", Subject: "example.v1.PAID", Count: 1},
	}
	dir := t.TempDir()
	first := filepath.Join(dir, "one")
	second := filepath.Join(dir, "two")
	if err := lint.SaveBaseline(first, &lint.Baseline{Findings: entries}); err != nil {
		t.Fatal(err)
	}
	// The same set in a different order must produce the same bytes.
	shuffled := []lint.BaselineEntry{entries[2], entries[0], entries[3], entries[1]}
	if err := lint.SaveBaseline(second, &lint.Baseline{Findings: shuffled}); err != nil {
		t.Fatal(err)
	}
	a, b := read(t, first), read(t, second)
	if a != b {
		t.Errorf("two orders of one set produced different files:\n%s\n---\n%s", a, b)
	}
	if !strings.Contains(a, "# Generated by stele.") {
		t.Errorf("the file does not say it is generated:\n%s", a)
	}
	// A count of one is what an entry already means, and writing it would be
	// noise in every line of a file people read.
	if strings.Contains(a, "count:") {
		t.Errorf("count: 1 was written out:\n%s", a)
	}
	got, err := lint.LoadBaseline(first)
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Findings) != len(entries) {
		t.Fatalf("round trip lost entries: wrote %d, read %d", len(entries), len(got.Findings))
	}
	for i, e := range got.Findings {
		if e.Count != 1 {
			t.Errorf("findings[%d]: count read back as %d; an absent count is one", i, e.Count)
		}
	}
}

// TestBaselineWriterNeverWritesWhatTheReaderRefuses is issue #1's lesson,
// applied to the second generated file this tool has. A writer that can emit
// a file the reader rejects leaves a repository with a baseline it cannot
// load and no repair but editing a generated file by hand.
func TestBaselineWriterNeverWritesWhatTheReaderRefuses(t *testing.T) {
	cases := []struct {
		name string
		in   lint.Baseline
		want string
	}{
		{
			name: "an entry naming no rule",
			in:   lint.Baseline{Findings: []lint.BaselineEntry{{Path: "a/v1/a.proto"}}},
			want: "rule",
		},
		{
			name: "an entry naming no file",
			in:   lint.Baseline{Findings: []lint.BaselineEntry{{Rule: "stele/syntax_declared"}}},
			want: "path",
		},
		{
			name: "a rule id that is not one",
			in:   lint.Baseline{Findings: []lint.BaselineEntry{{Rule: "syntax_declared", Path: "a/v1/a.proto"}}},
			want: "namespace",
		},
		{
			name: "one subject recorded twice",
			in: lint.Baseline{Findings: []lint.BaselineEntry{
				{Rule: "stele/enum_value_prefix", Path: "a/v1/a.proto", Subject: "a.v1.PAID"},
				{Rule: "stele/enum_value_prefix", Path: "a/v1/a.proto", Subject: "a.v1.PAID", Count: 2},
			}},
			want: "twice",
		},
		{
			name: "a count that is not a count",
			in: lint.Baseline{Findings: []lint.BaselineEntry{
				{Rule: "stele/enum_value_prefix", Path: "a/v1/a.proto", Subject: "a.v1.PAID", Count: -1},
			}},
			want: "count",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), lint.BaselineName)
			err := lint.SaveBaseline(path, &c.in)
			if err == nil {
				t.Fatalf("wrote a baseline it would refuse to read")
			}
			if !strings.Contains(err.Error(), c.want) {
				t.Errorf("the error does not name %q: %v", c.want, err)
			}
			if _, statErr := os.Stat(path); statErr == nil {
				t.Errorf("a refused write left a file behind")
			}
		})
	}
}

// TestBaselineParsingIsStrict holds it to the manifest's and the lock's
// standard: a key outside the format is an error naming that key, not a line
// that silently does nothing.
func TestBaselineParsingIsStrict(t *testing.T) {
	cases := map[string]string{
		"an unknown key":            "version: 1\nfindings:\n  - rule: stele/syntax_declared\n    path: a.proto\n    severity: warning\n",
		"a missing version":         "findings:\n  - rule: stele/syntax_declared\n    path: a.proto\n",
		"a version from the future": "version: 99\nfindings: []\n",
	}
	for name, body := range cases {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), lint.BaselineName)
			if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
				t.Fatal(err)
			}
			if _, err := lint.LoadBaseline(path); err == nil {
				t.Fatal("accepted a file outside the format")
			}
		})
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}
