package lockfile_test

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/thegorangers/stele/internal/lockfile"
)

const exampleSHA = "0123456789abcdef0123456789abcdef01234567"

// The ref is load-bearing: when a pinned SHA becomes unreachable, the message
// has to be able to name the branch the pin came from.
func TestSaveLoad_KeepsRefBesideSHA(t *testing.T) {
	path := filepath.Join(t.TempDir(), "stele.lock")
	e := lockfile.Entry{
		Name: "example",
		Git:  "https://example.com/owner/repo.git",
		Ref:  "release-2",
		SHA:  exampleSHA,
	}
	if err := lockfile.Save(path, &lockfile.Lock{Version: lockfile.Version, Deps: []lockfile.Entry{e}}); err != nil {
		t.Fatalf("Save: %v", err)
	}
	got, err := lockfile.Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(got.Deps) != 1 {
		t.Fatalf("want 1 entry, got %d", len(got.Deps))
	}
	if got.Deps[0].Ref != "release-2" || got.Deps[0].SHA != exampleSHA {
		t.Fatalf("ref/sha not round-tripped: %+v", got.Deps[0])
	}
}

// The lock is reviewed in merge requests, so its bytes must not depend on map
// iteration order.
func TestSave_IsDeterministic(t *testing.T) {
	deps := []lockfile.Entry{
		{Name: "example", Git: "https://example.com/owner/repo.git", Ref: "main", SHA: exampleSHA},
		{Name: "another", Git: "https://example.com/owner/other.git", Ref: "main", SHA: exampleSHA},
	}
	var first []byte
	for i := 0; i < 20; i++ {
		path := filepath.Join(t.TempDir(), "stele.lock")
		// Entries are given out of order on purpose.
		if err := lockfile.Save(path, &lockfile.Lock{Version: lockfile.Version, Deps: deps}); err != nil {
			t.Fatalf("Save: %v", err)
		}
		b, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if first == nil {
			first = b
			continue
		}
		if string(b) != string(first) {
			t.Fatalf("serialisation is not stable:\n--- first ---\n%s\n--- run %d ---\n%s", first, i, b)
		}
	}
	if !strings.Contains(string(first), "another") {
		t.Fatalf("unexpected lock body:\n%s", first)
	}
}

func TestLoad_UnknownKeyIsAnErrorNamingIt(t *testing.T) {
	cases := map[string]string{
		"top level": "version: 1\nspurious: 1\n",
		"entry":     "version: 1\ndeps:\n  - name: example\n    spurious: 1\n",
	}
	for name, body := range cases {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "stele.lock")
			if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
				t.Fatal(err)
			}
			_, err := lockfile.Load(path)
			if err == nil {
				t.Fatal("an unknown key must be an error")
			}
			if !strings.Contains(err.Error(), "spurious") {
				t.Fatalf("error must name the key, got %v", err)
			}
		})
	}
}

func TestLoad_RejectsUnsupportedVersion(t *testing.T) {
	path := filepath.Join(t.TempDir(), "stele.lock")
	if err := os.WriteFile(path, []byte("version: 99\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := lockfile.Load(path); err == nil {
		t.Fatal("an unsupported lock version must be an error")
	}
}

// A plugin's version decides the generated bytes as surely as a dependency's
// commit does, so it belongs in the same file.
func TestSaveLoad_Plugins(t *testing.T) {
	path := filepath.Join(t.TempDir(), "stele.lock")
	in := &lockfile.Lock{
		Version: lockfile.Version,
		Plugins: []lockfile.Plugin{
			{Name: "protoc-gen-go-grpc", Module: "google.golang.org/grpc/cmd/protoc-gen-go-grpc", Version: "v1.6.0"},
			{Name: "protoc-gen-dart", Version: "unknown"},
		},
	}
	if err := lockfile.Save(path, in); err != nil {
		t.Fatalf("Save: %v", err)
	}
	out, err := lockfile.Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	want := []lockfile.Plugin{
		{Name: "protoc-gen-dart", Version: "unknown"},
		{Name: "protoc-gen-go-grpc", Module: "google.golang.org/grpc/cmd/protoc-gen-go-grpc", Version: "v1.6.0"},
	}
	if !reflect.DeepEqual(out.Plugins, want) {
		t.Errorf("plugins:\n got %+v\nwant %+v", out.Plugins, want)
	}
}

func TestLoad_PluginEntryValidated(t *testing.T) {
	path := filepath.Join(t.TempDir(), "stele.lock")
	body := "version: 1\nplugins:\n  - module: example.com/x\n    version: v1.0.0\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	_, err := lockfile.Load(path)
	if err == nil || !strings.Contains(err.Error(), "plugins[0].name") {
		t.Fatalf("Load: expected a complaint about the missing name, got %v", err)
	}
}

// The pin is the SHA, and a SHA is already a cryptographic hash of the tree it
// names. Re-hashing the files it covers records nothing git has not recorded,
// so the lock does not carry them.
func TestSave_RecordsOnlyTheAddressOfEachDependency(t *testing.T) {
	path := filepath.Join(t.TempDir(), "stele.lock")
	in := &lockfile.Lock{Version: lockfile.Version, Deps: []lockfile.Entry{{
		Name: "example",
		Git:  "https://example.com/owner/repo.git",
		Ref:  "main",
		SHA:  exampleSHA,
	}}}
	if err := lockfile.Save(path, in); err != nil {
		t.Fatalf("Save: %v", err)
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, gone := range []string{"files:", "modules:", "manifest:"} {
		if strings.Contains(string(b), gone) {
			t.Errorf("the lock still carries %q:\n%s", gone, b)
		}
	}
	for _, want := range []string{"name: example", "ref: main", "sha: " + exampleSHA} {
		if !strings.Contains(string(b), want) {
			t.Errorf("the lock does not carry %q:\n%s", want, b)
		}
	}
}

// Locks written before the hashes were dropped exist on disk. Reading one must
// keep working, and writing it back must leave the old blocks behind.
func TestLoad_AcceptsALockWrittenBeforeTheHashesWereDropped(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "stele.lock")
	body := "version: 1\ndeps:\n" +
		"  - name: example\n" +
		"    git: https://example.com/owner/repo.git\n" +
		"    ref: main\n" +
		"    sha: " + exampleSHA + "\n" +
		"    modules:\n      - proto\n" +
		"    manifest: stele.yaml\n" +
		"    files:\n" +
		"      proto/a.proto: " + exampleSHA + "\n" +
		"      stele.yaml: " + exampleSHA + "\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	l, err := lockfile.Load(path)
	if err != nil {
		t.Fatalf("an existing lock must still load: %v", err)
	}
	if len(l.Deps) != 1 || l.Deps[0].SHA != exampleSHA || l.Deps[0].Ref != "main" {
		t.Fatalf("the address must survive the read: %+v", l.Deps)
	}
	rewritten := filepath.Join(dir, "rewritten.lock")
	if err := lockfile.Save(rewritten, l); err != nil {
		t.Fatalf("Save: %v", err)
	}
	b, err := os.ReadFile(rewritten)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(b), "files:") || strings.Contains(string(b), "modules:") {
		t.Errorf("rewriting must drop the old blocks:\n%s", b)
	}
}

// The lock records which tier each plugin came from and the data that
// identifies it there, so that a reader can tell a pinned plugin from a found
// one without going back to the manifest.
func TestSaveLoad_PluginTiers(t *testing.T) {
	path := filepath.Join(t.TempDir(), "stele.lock")
	in := &lockfile.Lock{
		Version: lockfile.Version,
		Plugins: []lockfile.Plugin{
			{Name: "protoc-gen-go", Origin: "managed", Module: "google.golang.org/protobuf/cmd/protoc-gen-go", Version: "v1.36.11"},
			{Name: "protoc-gen-dart", Origin: "url", OS: "linux", Arch: "amd64", URL: "https://example.com/dart.tar.gz", SHA256: "abc", ArchivePath: "bin/protoc-gen-dart", Version: "unknown"},
			{Name: "protoc-gen-house", Origin: "file", Path: "tools/protoc-gen-house", Version: "unknown"},
			{Name: "protoc-gen-found", Origin: "path", Version: "unknown"},
		},
	}
	if err := lockfile.Save(path, in); err != nil {
		t.Fatalf("Save: %v", err)
	}
	out, err := lockfile.Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	want := []lockfile.Plugin{
		{Name: "protoc-gen-dart", Origin: "url", OS: "linux", Arch: "amd64", URL: "https://example.com/dart.tar.gz", SHA256: "abc", ArchivePath: "bin/protoc-gen-dart", Version: "unknown"},
		{Name: "protoc-gen-found", Origin: "path", Version: "unknown"},
		{Name: "protoc-gen-go", Origin: "managed", Module: "google.golang.org/protobuf/cmd/protoc-gen-go", Version: "v1.36.11"},
		{Name: "protoc-gen-house", Origin: "file", Path: "tools/protoc-gen-house", Version: "unknown"},
	}
	if !reflect.DeepEqual(out.Plugins, want) {
		t.Errorf("plugins:\n got %+v\nwant %+v", out.Plugins, want)
	}
}

func TestLoad_PluginOriginValidated(t *testing.T) {
	path := filepath.Join(t.TempDir(), "stele.lock")
	body := "version: 1\nplugins:\n  - name: protoc-gen-x\n    origin: telepathy\n    version: unknown\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := lockfile.Load(path); err == nil || !strings.Contains(err.Error(), "telepathy") {
		t.Fatalf("Load: expected a complaint naming the origin, got %v", err)
	}
}

// A downloaded plugin is pinned to bytes, and bytes are per-platform. The lock
// records which platform's entry this run used, so that a lock reviewed on one
// machine says which machine produced it.
func TestSaveLoad_PluginDownloadRecordsThePlatform(t *testing.T) {
	path := filepath.Join(t.TempDir(), "stele.lock")
	in := &lockfile.Lock{
		Version: lockfile.Version,
		Plugins: []lockfile.Plugin{{
			Name: "protoc-gen-dart", Origin: lockfile.OriginURL, Version: "unknown",
			OS: "linux", Arch: "amd64",
			URL: "https://example.com/dart-linux-x64.tar.gz", SHA256: "abc",
			ArchivePath: "bin/protoc-gen-dart",
		}},
	}
	if err := lockfile.Save(path, in); err != nil {
		t.Fatalf("Save: %v", err)
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "os: linux") || !strings.Contains(string(b), "arch: amd64") {
		t.Errorf("the lock does not name the platform:\n%s", b)
	}
	out, err := lockfile.Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if !reflect.DeepEqual(out.Plugins, in.Plugins) {
		t.Errorf("plugins:\n got %+v\nwant %+v", out.Plugins, in.Plugins)
	}
}

// A url record without a platform would say which bytes ran without saying
// which machine they ran on, which is the half-record this shape exists to
// prevent.
func TestLoad_PluginDownloadWithoutAPlatformIsRejected(t *testing.T) {
	path := filepath.Join(t.TempDir(), "stele.lock")
	body := "version: 1\nplugins:\n  - name: protoc-gen-dart\n    origin: url\n    version: unknown\n" +
		"    url: https://example.com/dart\n    sha256: abc\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := lockfile.Load(path); err == nil || !strings.Contains(err.Error(), "platform") {
		t.Fatalf("Load: expected a complaint about the missing platform, got %v", err)
	}
}
