// Package config parses and validates the stele.yaml manifest.
package config

import (
	"github.com/thegorangers/stele/internal/managed"
	"github.com/thegorangers/stele/internal/plugin"
)

// File is a parsed stele.yaml manifest.
type File struct {
	// Version of the manifest format. Only 1 is supported.
	Version int `yaml:"version"`
	// Modules are the proto modules owned by this repository. Each path is an
	// import root: imports are resolved relative to it.
	Modules []Module `yaml:"modules"`
	// Deps are proto modules taken from other repositories.
	Deps []Dep `yaml:"deps"`
	// Generate lists the code generation targets.
	Generate []GenTarget `yaml:"generate"`
	// Lint configures the contract lint. Absent means every rule at its own
	// default over every file this repository owns.
	Lint *Lint `yaml:"lint"`
}

// Module is a proto module owned by this repository.
type Module struct {
	// Path is the directory of the module, relative to the manifest.
	Path string `yaml:"path"`
}

// Dep is a proto module taken from another repository.
type Dep struct {
	// Name identifies the dependency inside this manifest.
	Name string `yaml:"name"`
	// Git is the address of the producing repository.
	Git string `yaml:"git"`
	// Ref is the commit SHA or, for updating runs, a branch or tag.
	Ref string `yaml:"ref"`
	// Module is the module of the producer to take, relative to its root.
	Module string `yaml:"module"`
	// Paths narrows what is taken, in coordinates relative to the root of the
	// producer's module. Accepts a single string or a list of strings. Absent
	// takes the module whole.
	//
	// It is honoured by resolution, so it decides what the build has: a file
	// outside it supplies no import path, is judged by no conflict rule and is
	// named by no drift report. What it narrows is what is OFFERED, not what
	// is reachable — a file it excluded is offered again if a file that
	// survived it imports it, since the import structure inside a producer's
	// module is the producer's business and not something a consumer's
	// manifest is asserting anything about. A path that selects no file is an
	// error naming what the module does supply.
	Paths []string `yaml:"paths"`
}

// GenTarget is one code generation target.
type GenTarget struct {
	// Name identifies the target on the command line.
	Name string `yaml:"name"`
	// Inputs selects the files to generate from.
	Inputs []Input `yaml:"inputs"`
	// Plugins are the code generators to run over those files.
	Plugins []Plugin `yaml:"plugins"`
	// Managed, when present, asks for managed-mode file options to be
	// synthesised into the descriptors handed to the plugins. Absent means
	// absent: no options are synthesised at all.
	Managed *Managed `yaml:"managed"`
}

// Managed configures the managed-mode file options of one generate target.
type Managed struct {
	// Override lists the file options to synthesise. Each entry names one
	// option and, optionally, the path it is scoped to; one option scoped to
	// one path twice is an error rather than a last-one-wins race, because one
	// of the two entries would describe output nothing ever has.
	Override []Override `yaml:"override"`
}

// Override is one managed-mode file option.
type Override struct {
	// FileOption is the name of the option, in the spelling the measured
	// configs use. Only the options this tool synthesises are accepted; an
	// unknown one is an error naming it, never a silent skip. It may appear
	// more than once, at most once per Path.
	FileOption string `yaml:"file_option"`
	// Path limits the override to the files under it, in the coordinates an
	// import statement uses. Empty applies it to every file.
	//
	// One file option may be overridden several times, once per path. A file
	// matched by more than one entry takes the LAST of them, which is what the
	// reference tool does — measured, not assumed; the measurement is written
	// down on managed.selectOverride. Order is therefore meaning, and this is
	// the one place in the manifest where it is.
	Path string `yaml:"path"`
	// Value is the value of the option.
	Value string `yaml:"value"`
}

// FileOptionGoPackagePrefix is the only file option this tool synthesises from
// configuration. The list is short on purpose: an option accepted here but not
// applied would be a promise the generated bytes do not keep.
const FileOptionGoPackagePrefix = "go_package_prefix"

// fileOptions are the accepted spellings of Override.FileOption.
var fileOptions = []string{FileOptionGoPackagePrefix}

// Config translates the manifest's managed block into the form the option
// synthesiser takes.
func (m *Managed) Config() managed.Config {
	var c managed.Config
	if m == nil {
		return c
	}
	for _, o := range m.Override {
		if o.FileOption == FileOptionGoPackagePrefix {
			// Appended, not assigned: one file option may be overridden once
			// per path, and which of several matching entries applies to a
			// file is decided by their order. See managed.selectOverride.
			c.GoPackagePrefix = append(c.GoPackagePrefix, managed.Override{Path: o.Path, Value: o.Value})
		}
	}
	return c
}

// Input selects the files one generation request is built from.
//
// It names either a local module of this repository or a declared dependency,
// and exactly one of the two. The second form exists because a consumer that
// owns no protos at all is not a corner case: two repositories of the measured
// surface generate every line they have from somebody else's repository, and
// without it their manifests cannot express a generate target.
//
// A dependency input takes the module the deps entry already named, and does
// not narrow it further. The producer's other module roots are in the resolved
// graph so that imports resolve, not because this manifest asked for them; a
// second module selector here would let a target generate code from a root no
// deps entry ever requested, which is exactly the widening the deps entry
// exists to prevent. Narrowing within that module is what paths is for.
type Input struct {
	// Module is the path of a module declared in Modules. Mutually exclusive
	// with Dep.
	Module string `yaml:"module"`
	// Dep is the name of a dependency declared in Deps. Mutually exclusive
	// with Module.
	Dep string `yaml:"dep"`
	// Paths narrows the selection, in coordinates relative to the root of the
	// referenced module — this repository's module for Module, the producer's
	// module named by the deps entry for Dep. Accepts a single string or a
	// list of strings.
	Paths []string `yaml:"paths"`
}

// Plugin is one code generator invocation.
//
// Where the binary comes from is declared, and there are four ways to declare
// it. They are ordered by how much of the answer the manifest gives, and the
// manifest states which one is in use rather than leaving it to be inferred:
//
//  1. Module plus Version. The tool installs that exact version into its own
//     cache and verifies the installed binary's own build metadata against it.
//     Only a Go program can be had this way.
//
//  2. Downloads. One entry per platform, each naming a url and the sha256 the
//     download must have. The tool takes the entry matching the machine it is
//     running on, downloads it — or an archive holding the binary, named by
//     ArchivePath — into its own cache, and verifies the digest before
//     anything is run. This is what makes a plugin that is not a Go program
//     genuinely pinnable, and most of them publish release binaries.
//
//     It is a list because a digest pins bytes and bytes are per-platform: one
//     url cannot serve linux/amd64 and darwin/arm64, and a single-url form
//     would work for whoever wrote the manifest and push the next developer
//     back onto an unpinned PATH lookup.
//
//  3. Path. An explicit path to a binary, relative to the manifest. It says
//     where the binary is and nothing about which build it is: no version can
//     be pinned, and none is claimed.
//
//  4. None of the above: the name is looked up on PATH, as it always was. The
//     tool did not choose that binary and does not pretend it did.
//
// Exactly one may be declared. Two would be two answers to a question with one
// answer, and whichever the tool honoured would leave the other in the file
// describing a binary that never ran.
type Plugin struct {
	// Local is the name of, or the path to, an executable plugin binary. It
	// stays the plugin's name even when Module is declared: it is what the
	// report and the errors call it.
	Local string `yaml:"local"`
	// Module is the Go module path of the command that provides the plugin,
	// as `go install` takes it. Empty means the binary comes from PATH.
	Module string `yaml:"module"`
	// Version is the version of Module to install. It must be exact: a
	// floating version would put the manifest back in the business of
	// generating different bytes on different days, which is the whole
	// problem a declared version exists to remove.
	Version string `yaml:"version"`
	// Downloads are the published binaries of this plugin, one entry per
	// platform. Exactly one entry may match the machine the tool runs on; no
	// matching entry is an error, never a fallback to PATH.
	Downloads []Download `yaml:"downloads"`
	// Path is an explicit path to a binary, interpreted relative to the
	// directory of the manifest. An absolute path is accepted and reported:
	// in a file that is committed and shared, it resolves on one machine.
	Path string `yaml:"path"`
	// Out is the directory the plugin writes to.
	Out string `yaml:"out"`
	// Opt are the plugin options. Accepts a single string or a list of strings.
	Opt []string `yaml:"opt"`
}

// Download is one published binary of a plugin, for one platform.
//
// OS and Arch are Go's own spellings — GOOS and GOARCH — because that is what
// the tool compares them against. Accepting a publisher's spelling instead
// (x64, macos, aarch64) would need a translation table, and a table nobody can
// audit is a place for a platform to be matched to the wrong bytes.
type Download struct {
	// OS is the GOOS the binary is for, as runtime.GOOS spells it.
	OS string `yaml:"os"`
	// Arch is the GOARCH the binary is for, as runtime.GOARCH spells it.
	Arch string `yaml:"arch"`
	// URL is where the binary, or an archive holding it, is downloaded from.
	// It is meaningless without SHA256: an address alone says where the bytes
	// came from, not which bytes they were.
	URL string `yaml:"url"`
	// SHA256 is the hex digest the download must have. It is checked before
	// the download is unpacked, run, or admitted to the cache.
	SHA256 string `yaml:"sha256"`
	// ArchivePath names the member to take when the download is an archive,
	// in the archive's own coordinates. An archive with no member named is
	// refused: guessing which of its files is the plugin would be a guess the
	// hash cannot protect anyone from.
	ArchivePath string `yaml:"archive_path"`
}

// Platform is the entry's platform as an error message writes it.
func (d Download) Platform() string { return d.OS + "/" + d.Arch }

// PluginDownloads translates manifest download entries into the resolver's own
// type.
//
// The two types are separate so that the resolver depends on nothing: it
// resolves a plugin for anyone who can describe one, including callers that
// never read a manifest. The translation therefore has to live somewhere, and
// it lives here — once. It was written twice before, in generation and in
// lint, and a third caller is what turns two copies into a habit.
func PluginDownloads(ds []Download) []plugin.Download {
	if len(ds) == 0 {
		return nil
	}
	out := make([]plugin.Download, 0, len(ds))
	for _, d := range ds {
		out = append(out, plugin.Download{
			OS: d.OS, Arch: d.Arch, URL: d.URL, SHA256: d.SHA256, ArchivePath: d.ArchivePath,
		})
	}
	return out
}

// Lint configures the contract lint.
//
// The block is optional, and its absence means every rule at its own default
// over every file this repository owns — not a lint that does nothing. A tool
// that had to be switched on in the manifest would be switched on by the
// repositories that need it least.
//
// The whole block exists for one reason: a repository adopting lint over
// contracts that were never linted has findings on the first run, and the
// mechanism it uses to get to a green build has to be one a reviewer sees.
// `severity: warning` in a file everybody reads is that mechanism.
// `allow_failure: true` in a CI job is the thing it replaces, and it is
// invisible from the repository the rules are about.
type Lint struct {
	// Ignore lists import paths no rule is applied to. See Config.
	Ignore []string `yaml:"ignore"`
	// Plugins are the rule plugins to load beside the built-in rules.
	Plugins []LintPlugin `yaml:"plugins"`
	// Rules is what this repository says about individual rules.
	Rules []LintRule `yaml:"rules"`
}

// LintPlugin is one rule plugin: a binary outside this tool that serves rules
// the lint runs beside its own.
//
// Where the binary comes from is declared on exactly the same terms as a code
// generation plugin's — the same four tiers, in the same words, with the same
// refusals — and the same code enforces it. Two vocabularies for one question
// would be two sets of mistakes to make, and the question is the same one:
// which bytes ran. See Plugin for what each tier means.
//
// A rule that is not pinned is worse than no rule: it can change what it says
// about a repository without anything in that repository changing, and the
// first anybody hears of it is a build that reddened overnight.
type LintPlugin struct {
	// Name identifies the plugin in this manifest and in every error about
	// it. It is not a rule id: one plugin may serve several rules, the ids
	// are the plugin's to declare, and this is the line a reader has to come
	// back and edit.
	Name string `yaml:"name"`
	// Module and Version are the managed tier, as Plugin describes it.
	Module  string `yaml:"module"`
	Version string `yaml:"version"`
	// Downloads are the published binaries of this plugin, one per platform.
	Downloads []Download `yaml:"downloads"`
	// Path is an explicit path to a binary, relative to the manifest.
	Path string `yaml:"path"`
	// Unpinned admits, in the manifest, that this plugin is whatever the
	// machine's PATH resolves the name to.
	//
	// It is the one place a rule plugin is declared on different terms from a
	// code generation plugin, and the difference is in the consequence rather
	// than in the vocabulary. Both tiers answer the same question — which
	// bytes ran — and a generator that answers it with "whatever is on this
	// machine" produces different generated code, which lands in the diff
	// somebody reviews. A rule that answers it that way produces a different
	// judgement, and a judgement leaves no artefact: the build reddens or
	// greens overnight and nothing in the repository explains it.
	//
	// So the tier stays spellable — removing it would fork a vocabulary that
	// is shared on purpose — and it is not usable by accident. Saying it here
	// is one reviewed line in a file people read, the same mechanism
	// `severity: warning` is, and the run says it out loud on every report and
	// every listing rather than leaving the reader to come back and check.
	Unpinned bool `yaml:"unpinned"`
}

// LintRule is what a repository says about one rule.
type LintRule struct {
	// ID names the rule, as `namespace/name`. An ID no rule carries is an
	// error naming it: the two ways that happens are a typo and a rule that
	// has been removed, and both mean this file claims a protection or an
	// exemption that does not exist.
	ID string `yaml:"id"`
	// Severity is what a finding of this rule costs: error, warning or off.
	// Empty means error, which is what an unconfigured rule already is.
	Severity string `yaml:"severity"`
	// Ignore lists import paths this rule alone is not applied to.
	Ignore []string `yaml:"ignore"`
}

// LintSeverities are the accepted spellings of LintRule.Severity, in the order
// an error message should list them.
//
// They are spelled here rather than taken from the lint engine because the
// dependency runs the other way: the engine reads manifests, so a manifest
// parser that read the engine would be a cycle. That the two agree is not left
// to inspection — a test in the lint package puts every spelling here through
// the engine's own parser, and every rule id shape here through the engine's
// own check.
var LintSeverities = []string{"error", "warning", "off"}
