// Package config parses and validates the stele.yaml manifest.
package config

import "github.com/thegorangers/stele/internal/managed"

// File is a parsed stele.yaml manifest.
type File struct {
	// Version of the manifest format. Only 1 is supported.
	Version int `yaml:"version"`
	// Modules are the proto modules owned by this repository. Each path is an
	// import root: imports are resolved relative to it.
	Modules []Module `yaml:"modules"`
	// Deps are proto modules taken from other repositories.
	Deps []Dep `yaml:"deps"`
	// Generate lists the code generation targets.
	Generate []GenTarget `yaml:"generate"`
}

// Module is a proto module owned by this repository.
type Module struct {
	// Path is the directory of the module, relative to the manifest.
	Path string `yaml:"path"`
}

// Dep is a proto module taken from another repository.
type Dep struct {
	// Name identifies the dependency inside this manifest.
	Name string `yaml:"name"`
	// Git is the address of the producing repository.
	Git string `yaml:"git"`
	// Ref is the commit SHA or, for updating runs, a branch or tag.
	Ref string `yaml:"ref"`
	// Module is the module of the producer to take, relative to its root.
	Module string `yaml:"module"`
	// Paths narrows what is taken, in coordinates relative to the root of the
	// producer's module. Accepts a single string or a list of strings.
	Paths []string `yaml:"paths"`
}

// GenTarget is one code generation target.
type GenTarget struct {
	// Name identifies the target on the command line.
	Name string `yaml:"name"`
	// Inputs selects the files to generate from.
	Inputs []Input `yaml:"inputs"`
	// Plugins are the code generators to run over those files.
	Plugins []Plugin `yaml:"plugins"`
	// Managed, when present, asks for managed-mode file options to be
	// synthesised into the descriptors handed to the plugins. Absent means
	// absent: no options are synthesised at all.
	Managed *Managed `yaml:"managed"`
}

// Managed configures the managed-mode file options of one generate target.
type Managed struct {
	// Override lists the file options to synthesise. Each entry names one
	// option; an option named twice is an error rather than a last-one-wins
	// race, because the two entries describe different output.
	Override []Override `yaml:"override"`
}

// Override is one managed-mode file option.
type Override struct {
	// FileOption is the name of the option, in the spelling the measured
	// configs use. Only the options this tool synthesises are accepted; an
	// unknown one is an error naming it, never a silent skip.
	FileOption string `yaml:"file_option"`
	// Path limits the override to the files under it, in the coordinates an
	// import statement uses. Empty applies it to every file.
	Path string `yaml:"path"`
	// Value is the value of the option.
	Value string `yaml:"value"`
}

// FileOptionGoPackagePrefix is the only file option this tool synthesises from
// configuration. The list is short on purpose: an option accepted here but not
// applied would be a promise the generated bytes do not keep.
const FileOptionGoPackagePrefix = "go_package_prefix"

// fileOptions are the accepted spellings of Override.FileOption.
var fileOptions = []string{FileOptionGoPackagePrefix}

// Config translates the manifest's managed block into the form the option
// synthesiser takes.
func (m *Managed) Config() managed.Config {
	var c managed.Config
	if m == nil {
		return c
	}
	for _, o := range m.Override {
		if o.FileOption == FileOptionGoPackagePrefix {
			c.GoPackagePrefix = managed.Override{Path: o.Path, Value: o.Value}
		}
	}
	return c
}

// Input selects the files one generation request is built from.
//
// It names either a local module of this repository or a declared dependency,
// and exactly one of the two. The second form exists because a consumer that
// owns no protos at all is not a corner case: two repositories of the measured
// surface generate every line they have from somebody else's repository, and
// without it their manifests cannot express a generate target.
//
// A dependency input takes the module the deps entry already named, and does
// not narrow it further. The producer's other module roots are in the resolved
// graph so that imports resolve, not because this manifest asked for them; a
// second module selector here would let a target generate code from a root no
// deps entry ever requested, which is exactly the widening the deps entry
// exists to prevent. Narrowing within that module is what paths is for.
type Input struct {
	// Module is the path of a module declared in Modules. Mutually exclusive
	// with Dep.
	Module string `yaml:"module"`
	// Dep is the name of a dependency declared in Deps. Mutually exclusive
	// with Module.
	Dep string `yaml:"dep"`
	// Paths narrows the selection, in coordinates relative to the root of the
	// referenced module — this repository's module for Module, the producer's
	// module named by the deps entry for Dep. Accepts a single string or a
	// list of strings.
	Paths []string `yaml:"paths"`
}

// Plugin is one code generator invocation.
type Plugin struct {
	// Local is the name of, or the path to, an executable plugin binary.
	Local string `yaml:"local"`
	// Out is the directory the plugin writes to.
	Out string `yaml:"out"`
	// Opt are the plugin options. Accepts a single string or a list of strings.
	Opt []string `yaml:"opt"`
}
